# Generated by Django 5.0.7 on 2024-09-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('پیش غذا', 'پیش غذا'), ('غذای اصلی', 'غذای اصلی'), ('دسر', 'دسر')], default='غذای اصلی', max_length=20)),
                ('name', models.CharField(max_length=70, verbose_name='اسم')),
                ('slug', models.SlugField(default='', max_length=70)),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('rate', models.IntegerField(default=100, verbose_name='امتیاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('time', models.IntegerField(verbose_name='زمان لازم')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='foods/', verbose_name='عکس')),
            ],
        ),
    ]
